In [2]:
import numpy as np

In [13]:
a = np.arange(12).reshape(4,3)

In [14]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [16]:
for row in a: 
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# Order and flags and op_flags('external_loop', 'readwrite')

In [35]:
for x in np.nditer(a, order= 'c'):  # Same as flat or flatten and it returns the pattern of row by row
    print(x)

0
1
4
9
16
25
36
49
64
81
100
121


In [36]:
for cell in a.flatten():  #or for cell in a.flat:
    print(cell)

0
1
4
9
16
25
36
49
64
81
100
121


In [37]:
for x in np.nditer(a, order= 'f'): # it returns the pattern of column by column(Called Fortran order)
    print(x)

0
9
36
81
1
16
49
100
4
25
64
121


In [38]:
for x in np.nditer(a, order = 'F', flags = ['external_loop']): # it coverts every column into row
    print(x)

[ 0  9 36 81]
[  1  16  49 100]
[  4  25  64 121]


In [39]:
b = a.reshape(6,2)
b

array([[  0,   1],
       [  4,   9],
       [ 16,  25],
       [ 36,  49],
       [ 64,  81],
       [100, 121]])

In [62]:
c = np.arange(12).reshape(2,6)
# op_flags : you can modify each element of the array by this flag
for x in np.nditer(c, op_flags = ['readwrite']):
    x[...] = x * x

In [69]:
c

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

# Iterate 2 array at the same time


In [107]:
p = np.arange(12).reshape(3,4)
q = np.arange(3).reshape(3,1)

In [108]:
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
q

array([[0],
       [1],
       [2]])

In [110]:
for x, y in np.nditer([p,q]):
    print(x, y)

0 0
1 0
2 0
3 0
4 1
5 1
6 1
7 1
8 2
9 2
10 2
11 2
